# Generated by Django 3.1.4 on 2020-12-17 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20201204_1159'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='sort_id',
            field=models.IntegerField(default=0, verbose_name='Порядок'),
        ),
    ]
